name: Docker-Image-Dev
on: 
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=dev
          # always generate latest tag on push

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
        
      - name: Build and push to DockerHub (arm64)
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.arm64
          platform: linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
      
        